### ISSUE TITLE
get_data.py

### ISSUE THREAD

**Issue by LHMphaphuli** [Energy-Data-Science-Collaboration-Forum/ps-demand-forecasting#2]
"   get_ted_forecast_from_elexon(data_dir, "2019-01-01", "2023-07-31")
    get_wind_forecast_from_elexon(data_dir, "2019-01-01", "2023-07-31")"

The data returned goes from February 2022 to January 2023. Please advise if there is additional data available

**Comment by adfi** [comment]
Hi @LHMphaphuli , I'll have a look at the code as there is definitely more data available. In the meantime you can also directly download this data from the source:

* TED:https://data.nationalgrideso.com/backend/dataset/8fbc8a09-06af-4c90-886f-d3025d38a349/resource/9847e7bb-986e-49be-8138-717b25933fbb/download/archive1dayahead.csv
* Wind: https://data.nationalgrideso.com/backend/dataset/fbe3701d-1487-443e-abe9-47a6c01ecce2/resource/7524ec65-f782-4258-aaf8-5b926c17b966/download/archive1dayaheadwind.csv

**Comment by adfi** [comment]
@LHMphaphuli I was too hasty in linking those datasets as they are indeed in a different format. The problem is actually with Elexon's new Insights API. It only provides data for the period you quoted. However Elexon's BM Reports API goes further back. Unfortunately the latter requires an API key so is more of an hassle to set up. 

I will provide you with more historical data and we'll have to align the data formats somehow.

**Comment by adfi** [comment]
Elexon have indicated they will be updating the historical datasets in due course.
